de_fhir_path_list=[
    "Person.Demographie.AdministrativesGeschlecht",
    "Person.Demographie.Geburtsdatum",
    "Person.Demographie.Adresse.Strassenanschrift.PLZ",
    "Person.PatientIn.Patienten-Identifikator.Patienten-Identifikator",
    "Fall.Einrichtungskontakt.Aufnahmeanlass",
    "Fall.Einrichtungskontakt.Aufnahmegrund",
    "Fall.Einrichtungskontakt.Entlassungsgrund",
    "Fall.Abteilungskontakt.Fachabteilungsschluessel",
    "Fall.Versorgungsstellenkontakt.Aufnahmenummer",
    "Fall.Versorgungsstellenkontakt.KontaktKlasse",
    "Fall.Versorgungsstellenkontakt.Beginndatum",
    "Fall.Versorgungsstellenkontakt.Enddatum",
    "Diagnose.ICD10GMDiagnoseKodiert.VollstaendigerDiagnosekode",
    "Prozedur.OPSProzedurKodiert.VollstaendigerProzedurenkode",
    "Laborbefund.Laboruntersuchung.Code"
]
