---
# (c) 2019 Lorenz Kapsner
title: |
  | Datenqualitätsanalyse des §21-Datensatzes: 
  | Überprüfung der ETL-Strecken zwischen Quellsystem (exportierte §21 Rohdaten) und Zielsystem (i2b2 Datenbank) 
  | Zeitraum `r substr(as.character(rv$dqa_numerical_results$statistics$EpisodeOfCare_period_end$target_data[1,])[2], 1, 4)` bis `r substr(as.character(rv$dqa_numerical_results$statistics$EpisodeOfCare_period_end$target_data[6,])[2], 1, 4)` 
  | 
  | Standort: `r rv$sitename` 
  | 
date: '`r format(Sys.time(), "%d %B %Y")`' 
geometry: 'left=2.5cm,right=2.5cm,top=2cm,bottom=2cm' 
output: 
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
    includes:
      in_header: "./_header/header.tex"
    template: "./_header/miracum.latex"
    keep_tex: true
    pandoc_args:  [
                    "--variable", "graphics=yes",
                    "--variable", "compact-title:yes"
                  ]
editor_options:
  chunk_output_type: console
---

```{r global_options, include=FALSE}
# include this to compile pdf
knitr::opts_chunk$set(echo=F)
options(tinytex.verbose = TRUE)
```

\newpage

# Analyse der numerischen Variablen  

```{r results='asis'}
# numerical results
renderResults(rv$dqa_numerical_results)
```


# Analyse der kategorialen Variablen  

```{r results='asis'}
# categorical results
renderResults(rv$dqa_categorical_results)
```


# Plausibilitätsprüfungen  

```{r results='asis'}
# plausi results
renderPlausis(rv$dqa_plausibility_results)
```

# Einfache ETL-Checks

## Numerische Variablen

```{r results='asis'}
# categorical results
kableTable(quickETLChecks(rv$dqa_numerical_results))
```

## Kategoriale Variablen

```{r results='asis'}
# categorical results
kableTable(quickETLChecks(rv$dqa_categorical_results))
```
