---
# miRacumDQA - The MIRACUM consortium's data quality assessment tool
# Copyright (C) 2019 Universitätsklinikum Erlangen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
title: "Überprüfung der ETL-Strecken zwischen Quellsystem (exportierte §21 Rohdaten) und Zielsystem (`r rv$db_target` Forschungsdatenrepository)  \nZeitraum `r rv$time_interval$start` bis `r rv$time_interval$end`"
author: "Datenqualitätsanalyse des §21-Datensatzes  \nStandort: `r rv$sitename`"
date: \today
geometry: 'left=2.5cm,right=2.5cm,top=2cm,bottom=2cm' 
output: 
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
    includes:
      in_header: "./_header/header.tex"
    template: "./_header/miracum.latex"
    keep_tex: true
    pandoc_args:  [
                    "--variable", "graphics=yes",
                    "--variable", "compact-title=yes"
                  ]
---

```{r global_options, include=FALSE}
# include this to compile pdf
knitr::opts_chunk$set(echo=F)
options(tinytex.verbose = TRUE)
```

\newpage

# Data Map

## Target Data System

```{r results='asis'}
renderDataMap(rv$datamap$target_data)
```

## Source Data System

```{r results='asis'}
renderDataMap(rv$datamap$source_data)
```

# Completeness 

## ETL Checks

```{r results='asis'}
kableTable(rv$checks$etl)
```

# Missings

```{r results='asis'}
kableTable(rv$completeness) %>%
  kableExtra::column_spec(c(2:5), width. = "1.5cm")
```

# Conformance Checks

## Value Conformance

```{r results='asis'}
kableTable(rv$checks$value_conformance)
```


\newpage

# Detailed Descriptive Analysis

```{r results='asis'}
renderResults(rv$results_descriptive, rv$conformance$value_conformance)
```

\newpage

# Plausibility Checks

## Uniqueness Plausibility

```{r results='asis'}
# plausi results
renderUniqPlausis(rv$results_plausibility_uniqueness)
```

## Atemporal Plausibility 

```{r results='asis'}
# plausi results
renderAtempPlausis(rv$results_plausibility_atemporal, rv$conformance$value_conformance)
```

\newpage

# Appendix

## R-Package Version 'DQAstats' 

```{r}
utils::packageVersion("DQAstats")
```


## SQLs Target Data System  

```{r}
for (i in names(rv$sql_target)){
  cat(paste0("  \nMDR key: ", i, "  \n  \n"))
  cat(paste0(rv$sql_target[[i]]))
  cat("  \n  \n")
}
```

