---
# miRacumDQA - The MIRACUM consortium's data quality assessment tool
# Copyright (C) 2019 Universitätsklinikum Erlangen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

title: |
  | Überprüfung der ETL-Strecken
  | Zeitraum 
  | 
  | 
  | Datenqualitätsanalyse des §21-Datensatzes: 
  | Standort: 
date: '`r format(Sys.time(), "%d %B %Y")`' 
geometry: 'left=2.5cm,right=2.5cm,top=2cm,bottom=2cm' 
output: 
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
    includes:
      in_header: "./_header/header.tex"
    template: "./_header/miracum.latex"
    keep_tex: true
    pandoc_args:  [
                    "--variable", "graphics=yes",
                    "--variable", "compact-title:yes"
                  ]
editor_options:
  chunk_output_type: console
---

```{r global_options, include=FALSE}
# include this to compile pdf
knitr::opts_chunk$set(echo=F)
options(tinytex.verbose = TRUE)
```

\newpage

# Deskriptive Analyse    

```{r results='asis'}
renderResults(descriptive_results)
```

# Plausibilitätsprüfungen  

```{r results='asis'}
# plausi results
renderPlausis(plausi_out)
```

# ETL-Checks

```{r results='asis'}
kableTable(quickETLChecks(descriptive_results))
```

# Conformance Checks

## Value Conformance

```{r results='asis'}
kableTable(quickValueConformanceChecks(conformance_out$value_conformance))
```

\newpage

# Anhang

## Verwendete SQL-Befehle  

```{r results='asis'}
# for (i in names(rv$sql)){
#   cat(paste0("  \n**MDR key: ", i, "**  \n  \n"))
#   cat(paste0(rv$sql[[i]]))
#   cat("  \n  \n")
# }
```
